Sprint 6
ClevertecFrontendLab/UTYFjs pull request #6
Opened 2024-04-10 17:50 UTC by UTYFjs

complete

2024-04-10 17:54 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/UTYFjs/1712771651/update-trainings-3_360x740.png)

2024-04-10 19:03 UTC, byshlata requested changes
Замечания по коду

2024-04-10 19:03 UTC, byshlata commented on src/services/training-api.ts
> +                    () => {};
все таки напиши плиз зачем ты это делаешь

2024-04-10 19:03 UTC, byshlata commented on src/types/training-types.ts
> +    inviteId: string | null;
Nunlleble\<T> = T | null

2024-04-10 19:03 UTC, byshlata commented on src/utils/sort-by-a-z-and-status-users.ts
> +        } else {
else тут не надо

2024-04-10 19:16 UTC, vvikota requested changes

2024-04-10 19:16 UTC, vvikota commented on src/components/button-drawer-training/drawer-footer-actions/drawer-footer-actions.tsx
> +    const handleAddExercise = () => {
const handleAddExercise = () => dispatch(addNewExerciseToCurrentTraining())

2024-04-10 19:16 UTC, vvikota commented on src/components/button-drawer-training/button-drawer-training.tsx
> +    const handleDrawerAction = async () => {
тут как то все очень сложно , может вообще эту функцию вынести в отдельный файлик как утилку

2024-04-10 19:16 UTC, vvikota commented on src/components/trainings/joint-trainings/invite/invite.css
> +
пробегись линтером, такие пробелы большие не только в этом месте

2024-04-10 19:16 UTC, vvikota commented on src/components/button-drawer-training/exercise-form/exercise-form.tsx
> +    const onChangeName = (value: string, index: number) => {
тут везде не нужны фигурные скобки

2024-04-10 19:16 UTC, vvikota commented on src/components/trainings/joint-trainings/partners-list/partners-list.tsx
> +                    grid={{
этот обьект в константу и вверх файлика поднять

2024-04-10 19:16 UTC, vvikota commented on src/components/trainings/my-trainings/training-list.tsx/training-list.css
> + .training-list-table .ant-table-tbody .ant-table-row .ant-table-cell:first-child{
на будущее , старайся писать селекторы покороче, 2-3 класса максимум

2024-04-10 21:20 UTC, ValadzkoAliaksei requested changes

2024-04-10 21:20 UTC, ValadzkoAliaksei commented on src/components/button-drawer-training/button-drawer-training.css
> +
![image](https://github.com/ClevertecFrontendLab/UTYFjs/assets/61273546/fd0f32c8-0d64-4a4a-b124-0675f12dabe3)
рейтинг обязателен

2024-04-10 21:20 UTC, ValadzkoAliaksei commented on src/components/button-drawer-training/button-drawer-training.css
> +.drawer-button__title-wrapper{
![image](https://github.com/ClevertecFrontendLab/UTYFjs/assets/61273546/99792f65-ce9a-4264-9d8a-ddc0e285b7fa)
фоток нет

2024-04-10 21:20 UTC, ValadzkoAliaksei commented on src/components/button-drawer-training/button-drawer-training.css
> +}
![image](https://github.com/ClevertecFrontendLab/UTYFjs/assets/61273546/cdaa660e-d7cd-4120-ad3c-03bd00cf977a)
кнопка все время задизейблена, не могу ничего поменять(

2024-04-11 08:59 UTC, UTYFjs commented on src/services/training-api.ts
> +                    () => {};
очень хочется обработать ошибку но не придумал как) это просто заглушка у меня. чтобы меньше падало. а что такие заглушки лучше не использовать?

2024-04-11 12:49 UTC, UTYFjs commented on src/components/trainings/joint-trainings/partner-card/partner-card.css
> +  padding: 16px 16px 8px;
чет меня занесло)

2024-04-11 12:50 UTC, UTYFjs commented on src/components/trainings/joint-trainings/partner-card/partner-card.tsx
> +    type: 'short' | 'full';
а по какому принципу вот такие вещи выносить в отдельные штуки?

2024-04-11 12:52 UTC, UTYFjs commented on src/components/button-drawer-training/button-drawer-training.css
> +
исправил

2024-04-11 12:56 UTC, UTYFjs commented on src/components/button-drawer-training/button-drawer-training.css
> +}
поймал такой случай что при изменении ТОЛЬКО даты рождения кнопка не раздизейбливалась - исправил. в остальных случаях у меня все раздизейбливалось. если проблема все еще имеет место быть напишите пожалуйста поподробнее про среду и в каких условиях это происходит.

2024-04-11 13:00 UTC, byshlata approved these changes

2024-04-11 14:20 UTC, vvikota approved these changes

2024-04-11 14:48 UTC, merged